version: '3.8'

services:
  hrhub.api:
    build:
      context: .
      dockerfile: src/HrHub.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_EnableDiagnostics=1
    tty: true 
